#!/usr/bin/python3

import json
from os import path
import requests
from sys import argv, exit
import tarfile



def make_tarfile(output_filename, source_dir):
    with tarfile.open(output_filename, "w:gz") as tar:
        tar.add(source_dir, arcname=path.basename(source_dir))



def get_target_address(Aqueduct):
	if len(argv) > 1:
		return argv[1]
	return Aqueduct['target']



Aqueduct = {}

try:
	f = open('debian/Aqueduct', 'r')
	Aqueduct = json.load(f)
	f.close()
except ValueError:
	print("Aqueduct file contains invalid json")
	exit(1)
except:
	print("Unable to read Aqueduct file (IE cannot find ./debian/Aqueduct)")
	exit(1)



if 'version' not in Aqueduct:
	print('ERROR: Expected Aqueduct file to have a key called version.')
	exit(1)

if Aqueduct['version'] < 1:
	print("WARNING: Aqueduct file version " + str(Aqueduct['version']) + " is a TEMPORARY and UNSTABLE specification. Do NOT use it in production.")
	#make_tarfile('../aqueduct-temp.tar.gz', '.')
	requests.post('http://localhost:5600/submit', {'file': open('../aqueduct-temp.tar.gz', 'rb')})

else:
	print("ERROR: Unrecognized Aqueduct format version. Perhaps this client is out of date?")
